name: pull_request
on:
  push:
    branches: []
  pull_request:
    branches: []

jobs:
  # 서브모듈 확인
  check-submodule:
    runs-on: ubuntu-latest
    steps:
      # 클론
      - uses: actions/checkout@v2
        if: github.event_name != 'pull_request'
        with:
          submodules: true
          ssh-key: ${{ secrets.SUBMODULE_PULL_KEY }}
          lfs: false
      - uses: actions/checkout@v2
        if: github.event_name == 'pull_request'
        with:
          ref: ${{ github.pull_request.head.sha }}
          submodules: true
          ssh-key: ${{ secrets.SUBMODULE_PULL_KEY }}
          lfs: false
      # Node.js 설치
      - uses: actions/setup-node@v1
        with:
          node-version: "14"
      - name: Install Dependencies
        run: yarn add typescript
      # Lib9c 확인
      - name: Check Lib9c
        run: npx ts-node scripts/checkSubmodule.ts Lib9c
      # Shared 확인
      - name: Check NineChronicles.RPC.Shared
        run: npx ts-node scripts/checkSubmodule.ts NineChronicles.RPC.Shared
